<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="13065" started-at="2023-04-23T06:04:52Z" finished-at="2023-04-23T06:05:05Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="13065" started-at="2023-04-23T06:04:52Z" finished-at="2023-04-23T06:05:05Z">
      <class name="testcases.LoginTest">
        <test-method status="PASS" signature="ReportSetUp()[pri:0, instance:testcases.LoginTest@7403c468]" name="ReportSetUp" is-config="true" duration-ms="510" started-at="2023-04-23T06:04:52Z" finished-at="2023-04-23T06:04:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReportSetUp -->
        <test-method status="PASS" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:testcases.LoginTest@7403c468]" name="SetUp" is-config="true" duration-ms="1642" started-at="2023-04-23T06:04:53Z" finished-at="2023-04-23T06:04:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.LoginTest.test1()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="test1()[pri:0, instance:testcases.LoginTest@7403c468]" name="test1" duration-ms="3430" started-at="2023-04-23T06:04:55Z" finished-at="2023-04-23T06:04:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:testcases.LoginTest@7403c468]" name="TearDown" is-config="true" duration-ms="83" started-at="2023-04-23T06:04:58Z" finished-at="2023-04-23T06:04:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:testcases.LoginTest@7403c468]" name="SetUp" is-config="true" duration-ms="1317" started-at="2023-04-23T06:04:58Z" finished-at="2023-04-23T06:04:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.LoginTest.test2()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="test2()[pri:0, instance:testcases.LoginTest@7403c468]" name="test2" duration-ms="4185" started-at="2023-04-23T06:04:59Z" finished-at="2023-04-23T06:05:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:testcases.LoginTest@7403c468]" name="TearDown" is-config="true" duration-ms="75" started-at="2023-04-23T06:05:04Z" finished-at="2023-04-23T06:05:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:testcases.LoginTest@7403c468]" name="SetUp" is-config="true" duration-ms="1381" started-at="2023-04-23T06:05:04Z" finished-at="2023-04-23T06:05:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.LoginTest.test4(java.lang.reflect.Method) throws com.codoid.products.exception.FilloException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="FAIL" signature="test4(java.lang.reflect.Method)[pri:0, instance:testcases.LoginTest@7403c468]" name="test4" duration-ms="81" started-at="2023-04-23T06:05:05Z" finished-at="2023-04-23T06:05:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.LoginTest.test4(java.lang.reflect.Method) throws com.codoid.products.exception.FilloException]]>
              </value>
            </param>
          </params>
          <exception class="com.codoid.products.exception.FilloException">
            <message>
              <![CDATA[Invalid Query - SELECT * FROM DATA WHERE TESTNAME = TEST4']]>
            </message>
            <full-stacktrace>
              <![CDATA[com.codoid.products.exception.FilloException: Invalid Query - SELECT * FROM DATA WHERE TESTNAME = TEST4'
at com.codoid.products.parser.SelectQueryParser.initializeQuery(SelectQueryParser.java:46)
at com.codoid.products.fillo.Select.getRecordset(Select.java:44)
at com.codoid.products.fillo.Connection.executeQuery(Connection.java:64)
at testcases.LoginTest.test4(LoginTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.codoid.products.exception.FilloException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:testcases.LoginTest@7403c468]" name="TearDown" is-config="true" duration-ms="80" started-at="2023-04-23T06:05:05Z" finished-at="2023-04-23T06:05:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="ReportClean()[pri:0, instance:testcases.LoginTest@7403c468]" name="ReportClean" is-config="true" duration-ms="259" started-at="2023-04-23T06:05:05Z" finished-at="2023-04-23T06:05:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReportClean -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
